In [1]:
import pandas as pd

In [4]:
!wget https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet

--2026-01-25 07:03:59--  https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet
Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 3.167.84.127, 3.167.84.228, 3.167.84.131, ...
Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|3.167.84.127|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1164775 (1.1M) [binary/octet-stream]
Saving to: ‘green_tripdata_2025-11.parquet’

green_tripdata_2025 100%[===================>]   1.11M  --.-KB/s    in 0.03s

2026-01-25 07:03:59 (36.1 MB/s) - ‘green_tripdata_2025-11.parquet’ saved [1164775/1164775]

In [5]:
!wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv

--2026-01-25 07:04:28--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-01-25T07%3A41%3A17Z&rscd=attachment%3B+filename%3Dtaxi_zone_lookup.csv&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-01-25T06%3A41%3A07Z&ske=2026-01-25T07%3A41%3A17Z&sks=b&skv=2018-11-09&sig=OdUi8tfpKjBQ%2FNKlVZgsd0DCXA%2BUlbvi3jRiWJbQRHk%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc2OTMyNDk2OCwibmJmIjoxNzY5MzI0NjY4LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.1UO1Oyr7UijV2o-v6uLpUOpQjzuzIVUnpgutHPdgrgE&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream [following]
--2026-01-25 07:04:28--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-01-25T07%3A41%3A17Z&rscd=attachment%3B+filename%3Dtaxi_zone_lookup.csv&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-01-25T06%3A41%3A07Z&ske=2026-01-25T07%3A41%3A17Z&sks=b&skv=2018-11-09&sig=OdUi8tfpKjBQ%2FNKlVZgsd0DCXA%2BUlbvi3jRiWJbQRHk%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc2OTMyNDk2OCwibmJmIjoxNzY5MzI0NjY4LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.1UO1Oyr7UijV2o-v6uLpUOpQjzuzIVUnpgutHPdgrgE&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12322 (12K) [application/octet-stream]
Saving to: ‘taxi_zone_lookup.csv.1’

taxi_zone_lookup.cs 100%[===================>]  12.03K  --.-KB/s    in 0s

2026-01-25 07:04:28 (57.8 MB/s) - ‘taxi_zone_lookup.csv.1’ saved [12322/12322]

In [27]:
dtype = {
    "RatecodeID": "Int64",
    "passenger_count": "Int64",
    "payment_type": "float64",
    "trip_type": "Int64",
    
}

In [64]:
df = pd.read_parquet("green_tripdata_2025-11.parquet")

In [48]:
!uv add fastparquet

Resolved 123 packages in 2.53s
Prepared 3 packages in 171ms
░░░░░░░░░░░░░░░░░░░░ [0/3] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 3 packages in 30ms0
 + cramjam==2.11.0
 + fastparquet==2025.12.0
 + fsspec==2026.1.0

In [49]:
from fastparquet import ParquetFile

pf = ParquetFile('green_tripdata_2025-11.parquet')

In [51]:
pf.head(nrows=4)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1,74,42,1,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1,1,0.0,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1,74,42,2,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2,1,0.0,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1,83,160,1,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1,1,0.0,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1,166,127,1,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1,1,0.0,0.0

In [36]:
# df = df.astype({"RatecodeID": "Int64",
#     "passenger_count": "Int64",
#     "payment_type": "Int64",
#     "trip_type": "Int64"})

In [65]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

In [42]:
df.shape

(46912, 21)

In [9]:
df.dtypes

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag               object
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [38]:
df['payment_type'].value_counts()

payment_type
1    31628
2     9341
3      286
4       86
5        2
Name: count, dtype: Int64

In [20]:
taxi_df = pd.read_csv("taxi_zone_lookup.csv.1")

In [21]:
taxi_df.dtypes

LocationID       int64
Borough         object
Zone            object
service_zone    object
dtype: object

In [22]:
taxi_df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [58]:
taxi_df.shape

(265, 4)

In [39]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [40]:
print(pd.io.sql.get_schema(df, name='green_tripdata_2025-11', con=engine))

CREATE TABLE "green_tripdata_2025-11" (
	"VendorID" INTEGER,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" BIGINT,
	"PULocationID" INTEGER,
	"DOLocationID" INTEGER,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type BIGINT,
	trip_type BIGINT,
	congestion_surcharge FLOAT(53),
	cbd_congestion_fee FLOAT(53)
)

In [62]:
df.to_sql(name='green_tripdata_2025_11', con=engine, if_exists='replace')

912

In [61]:
from tqdm.auto import tqdm
first_chunk = next(pf.iter_row_groups())

first_chunk.head(0).to_sql(
    name="green_tripdata_2025_11",
    con=engine,
    if_exists="replace"
)

print("Table created")

first_chunk.to_sql(
    name="green_tripdata_2025_11",
    con=engine,
    if_exists="append"
)

print("Inserted first chunk:", len(first_chunk))

# for df_chunk in tqdm(df_iter):
for df_chunk in tqdm(pf.iter_row_groups()):
    df_chunk.to_sql(
        name="green_tripdata_2025_11",
        con=engine,
        if_exists="append"
    )
    print("Inserted chunk:", len(df_chunk))

Table created
Inserted first chunk: 46912

0it [00:00, ?it/s]

Inserted chunk: 46912

In [60]:
taxi_df.to_sql(name='taxi_zone_lookup', con=engine, if_exists='replace')

265

In [67]:
uv run jupyter nbconvert --to=script assignment-notebook.ipynb

/workspaces/data-engineering-zoomcamp/pipeline/.venv/bin/python3: No module named uv
Note: you may need to restart the kernel to use updated packages.